### ISSUE TITLE
Incorrect documentation

### ISSUE THREAD

**Issue by denilsonsa** [haya14busa/vim-easyoperator-phrase#4]
The documentation seems to be copy-pasted from vim-easyoperator-line, and thus it still says the mapping uses the `l` (lowecase L) key, instead of the actual `p` key (which I only found because I looked at the source-code.

Please review the documentation and fix anything that is wrong.

**Comment by haya14busa** [comment]
Thanks for your report, @denilsonsa 

I fixed it.
